services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: limber
      POSTGRES_PASSWORD: limber1234
      POSTGRES_DB: limberdb
      TZ: Asia/Seoul   # ← 한국 시간대 설정
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - limber-net
#    restart: unless-stopped
#    profiles: [ "db" ]

  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    depends_on:
      - postgres
    environment:
      TZ: "Asia/Seoul"
      JAVA_TOOL_OPTIONS: "-Duser.timezone=Asia/Seoul"
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/limberdb
      SPRING_DATASOURCE_USERNAME: limber
      SPRING_DATASOURCE_PASSWORD: limber1234
    ports:
      - "8888:8888"
    networks:
      - limber-net

volumes:
  pgdata:

networks:
  limber-net:
