version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: limber-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/limberdb
      SPRING_DATASOURCE_USERNAME: limber
      SPRING_DATASOURCE_PASSWORD: limber1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - limber-net

  postgres:
    image: postgres:15
    container_name: limber-postgres
    restart: always
    environment:
      POSTGRES_DB: limberdb
      POSTGRES_USER: limber
      POSTGRES_PASSWORD: limber1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - limber-net

volumes:
  pgdata:

networks:
  limber-net:
    driver: bridge
