spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    write:
      url: jdbc:postgresql://localhost:5432/limberdb
      username: limber
      password: limber1234
    read:
      url: jdbc:postgresql://localhost:5432/limberdb
      username: limber
      password: limber1234

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
